# This is a basic workflow to help you get started with Actions

name: CI-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: build container
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF##*/}
        docker build -t ${{secrets.DOCKER_USERNAME}}/membot-discord:latest --build-arg bot_version=${git_branch}.${git_hash} .

    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}

    - name: push image
      run: docker push ${{secrets.DOCKER_USERNAME}}/membot-discord:latest

    - name: deploy image
      uses: satak/webrequest-action@master
      with:
        url: http://jemand771.net/hook/?${{secrets.DEPLOY_HOOK_MASTER}}
        method: GET
